### ISSUE TITLE
./schema/generate.sh failed

### ISSUE THREAD

**Issue by shinexia** [alibaba/MNN#37]
## Reproduction step:

```
git clone 
cd path/to/mnn
./schema/generate.sh
```

## Outputs:
```
$ ./schema/generate.sh
*** building flatc ***
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: Error executing cmake::LoadCache(). Aborting.

*** cleaning up ***
*** generating fbs under default ***
xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Generating Schema...
*** building flatc ***
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: Error executing cmake::LoadCache(). Aborting.

xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
./generate_schema.sh: line 39: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Done!
*** done ***
```

## Environments

ubuntu 18.04
gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
cmake version 3.10.2
export CMAKE_ROOT=/usr/share/cmake-3.10

**Comment by czy2014hust** [comment]
/schema/generate.sh ==> cd schema && ./generate.sh

**Comment by shinexia** [comment]
> /schema/generate.sh ==> cd schema && ./generate.sh

same results

**Comment by shinexia** [comment]
build succeed on centos 7 (docker), with:
cmake version 2.8.12.2
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

but still failed on ubuntu 18.04

**Comment by shinexia** [comment]
fixed after running this:
sudo apt install extra-cmake-modules

**Comment by JaySimple** [comment]
Hi, sry to disturb. A similar problem occurs in my case, and the following is the output:

root@6d3edda80bab:~/MNN# ./schema/generate.sh
*** building flatc ***
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
*** cleaning up ***
*** generating fbs under default ***
xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Generating Schema...
*** building flatc ***
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
./generate_schema.sh: line 39: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Done!
*** done ***

Environments:
linux 16.04(docker)
cmake version 3.13.3
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11)

I have installed extra-cmake-modules, but no changes. Anybody help me out? Thx.

**Comment by li-qing** [comment]
> Unix Makefiles

perhaps make is not installed in your system? try `sudo apt-get install make`.

**Comment by JaySimple** [comment]
> > Unix Makefiles
> 
> perhaps make is not installed in your system? try `sudo apt-get install make`.

Thx. I have installed the make, but the problem remains. Anyway, I read the script generate.sh,  implement the commands one by one, and then success to complete this step. A little strange, there may be some points i missed.
